// <auto-generated />
using System;
using ChatApplication.Controller;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChatApplication.Migrations
{
    [DbContext(typeof(ServerDatabase))]
    [Migration("20240415072444_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChatApplication.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("ClientIP")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("FromIP")
                        .HasColumnType("text");

                    b.Property<string>("Msg")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverIP")
                        .HasColumnType("text");

                    b.Property<bool>("Seen")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ClientIP");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("WindowsFormsApp3.Client", b =>
                {
                    b.Property<string>("IP")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePath")
                        .HasColumnType("text");

                    b.Property<int>("UnseenMessages")
                        .HasColumnType("int");

                    b.HasKey("IP");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ChatApplication.Message", b =>
                {
                    b.HasOne("WindowsFormsApp3.Client", null)
                        .WithMany("UnSeenMessagesList")
                        .HasForeignKey("ClientIP");
                });
#pragma warning restore 612, 618
        }
    }
}
